### ISSUE TITLE
Getting an error when trying to use

### ISSUE THREAD

**Issue by AsWali** [dgoguerra/pokego-scan#3]
ERROR in ./~/request/~/tough-cookie/lib/cookie.js
Module not found: Error: Cannot resolve module 'net' in C:\Users\sardo\Desktop\Develop\my-project\node_modules\request\node_modules\tough-cookie\lib
 @ ./~/request/~/tough-cookie/lib/cookie.js 32:10-24

ERROR in ./~/forever-agent/index.js
Module not found: Error: Cannot resolve module 'net' in C:\Users\sardo\Desktop\Develop\my-project\node_modules\forever-agent
 @ ./~/forever-agent/index.js 6:10-24

ERROR in ./~/forever-agent/index.js
Module not found: Error: Cannot resolve module 'tls' in C:\Users\sardo\Desktop\Develop\my-project\node_modules\forever-agent
 @ ./~/forever-agent/index.js 7:10-24

ERROR in ./~/request/lib/har.js
Module not found: Error: Cannot resolve module 'fs' in C:\Users\sardo\Desktop\Develop\my-project\node_modules\request\lib
 @ ./~/request/lib/har.js 3:9-22

ERROR in ./~/tunnel-agent/index.js
Module not found: Error: Cannot resolve module 'net' in C:\Users\sardo\Desktop\Develop\my-project\node_modules\tunnel-agent
 @ ./~/tunnel-agent/index.js 3:10-24

ERROR in ./~/tunnel-agent/index.js
Module not found: Error: Cannot resolve module 'tls' in C:\Users\sardo\Desktop\Develop\my-project\node_modules\tunnel-agent
 @ ./~/tunnel-agent/index.js 4:10-24

How do i fix this issue ? Also wont you get the no cross origin error ? Because thats what I get when directly calling their url

**Comment by dgoguerra** [comment]
Hi, are you by any chance trying to bundle the package with Webpack? It looks like those errors may come from the `request` package, which [apparently needs to be configured](https://github.com/request/request/issues/1529) in a special way to load it from Webpack. If you take a look at those errors they look pretty similar to yours.

Anyway, you are right, this will most likely fail when loaded from a browser due to CORS. Sorry about that, I should have specified it better but this package is made for Node, and has only been tested there.

I hope it fits your needs anyway!
